### ISSUE TITLE
Kick command not applying rejoin time penalty

### ISSUE THREAD

**Issue by TheRadiumDude** [CreepPork/Beacon#6]
Using `kick` in Beacon to remove a troublesome player remotely does not seem to correctly apply the time penalty *(90 seconds or so)* that must pass before the kicked player can rejoin.

Supposedly, the penalty was applied in some circumstances, but in practice very rarely seems to occur.

**Comment by Radiumio** [comment]
Seems to work now, strangely, the original issue doesn't seem apparent or common anymore.

**Comment by CreepPork** [comment]
Closing as seems to have always worked but it's just Arma's weird behaviour.
